---
- hosts: VotrenomdeNode # faite corespondre le hostname avec le fichier /etc/ansible/hosts
  strategy: free
  tasks:

    - name: preparation pour containerd
      win_command: powershell.exe Install-WindowsFeature Containers
    - name: prepartion de hyper-V    
      win_command: powershell.exe Install-WindowsFeature Hyper-V
    - name: deuxième preparation pour hyper-V
      win_command: powershell.exe Install-WindowsFeature Hyper-V-Powershell
    - name: configuration des règles de firewall
      win_command: powershell.exe Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
    - name: reboot pour appliquer les paramètre
      win_command: powershell.exe Restart-Computer -force

  
    - name: on attend la fin du reboot
      wait_for_connection:
        delay: 180
        timeout: 2000


    
    - name: Telechargement de containerd
      win_command: powershell.exe wget https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-windows-amd64.tar.gz -OutFile containerd.windows.tar.gz

    - name: décompression le fichier d'installation containerd
      win_command: powershell.exe tar -xvf containerd.windows.tar.gz

    - name: envoie des executable containerd vers son repertoir de travail
      win_command: powershell.exe Copy-Item -Path "./bin/" -Destination "$Env:ProgramFiles/containerd" -Recurse -Force

    - name: recuperation de containerd.exe pour mettre en place la config
      win_command: powershell.exe cp "./bin/containerd.exe"  

    - name: recuperation de la config
      win_command: powershell.exe ./containerd.exe config default | Out-File config.toml -Encoding ascii 

    - name: envoie la config dans le repertoir de travail de containerd
      win_command: powershell.exe mv .\config.toml  $Env:ProgramFiles/containerd/config.toml 




    - name: enregistrer le service containerd
      win_command: ./containerd.exe --register-service

    - name: Allumer containerd
      win_command: Powershell.exe Start-Service containerd


    - name: crée le répertoire de travail de kubernetes
      win_command: powershell.exe mkdir c:/k


    - name: téléchrager calico et kubernetes
      win_command: powershell.exe wget https://github.com/projectcalico/calico/releases/download/v3.27.2/install-calico-windows.ps1 -OutFile c:/install-calico-windows.ps1

    - name: télécharger contenue pour calico
      win_command: powershell.exe wget https://github.com/projectcalico/calico/releases/download/v3.27.2//calico-windows-v3.27.2.zip -OutFile c:/calico-windows.zip

    - name: téléchargement kuberentes script
      win_command: powershell.exe wget https://github.com/Microsoft/SDN/raw/master/Kubernetes/windows/hns.psm1 -OutFile c:/k/hns.psm1


    - name: Remplacer bin_dir  dans la config de containerd
      win_lineinfile:
        path: "C:/Program Files/containerd/config.toml"
        regexp: '      bin_dir'
        line: '      bin_dir = "C:\\k\\cni\\"'

    - name: Remplacer conf_dir dans la config de containerd
      win_lineinfile:
        path: "C:/Program Files/containerd/config.toml"
        regexp: '      conf_dir'
        line: '      conf_dir = "C:\\k\\cni\\config"'


    - name: recupération du kubeconfig pour l'intialisation de kubernetes
      win_copy:
        src: /root/.kube/config
        dest: c:/k/config

  
    - name: creation du répertoir cni pour l'initalisation
      win_command: powershell.exe mkdir cni

    - name: creation du répertoir cni bin pour l'initalisation
      win_command: powershell.exe mkdir cni/bin

    - name: creation du répertoir cni conf  pour l'initalisation
      win_command: powershell.exe mkdir cni/conf

    - name: installation de calico et kubernetes
      win_command: powershell.exe c:/install-calico-windows.ps1 -KubeVersion {{kubernetes_version}} -ServiceCidr 10.96.0.0/12 -DNSServerIPs 10.96.0.10
      ignore_unreachable: True
      ignore_errors: True
      timeout: 600

    - name: on attend la fin du téléchargement
      wait_for_connection:
         delay: 300
         timeout: 360

    - name: Remplacer la configuration cni bin_dir de calico
      win_lineinfile:
        path: "C:/CalicoWindows/config.ps1"
        regexp: 'ContainerdCniBinDir'
        line: '    Set-EnvVarIfNotSet -var "CNI_BIN_DIR" -defaultValue "c:\k\cni"'



    - name: Remplacer la configuration cni conf_dir de calico
      win_lineinfile:
        path: "C:/CalicoWindows/config.ps1"
        regexp: 'ContainerdCniConfDir'
        line: '    Set-EnvVarIfNotSet -var "CNI_CONF_DIR" -defaultValue "c:\k\cni\config"'


    - name: démarrage calico
      win_command: powershell.exe c:/CalicoWindows/install-calico.ps1
  
    - name: démarrage kubernetes
      win_command: powershell.exe C:/CalicoWindows/kubernetes/install-kube-services.ps1


    - name: reboot
      win_command: powershell.exe Restart-Computer -force
      ignore_errors: True

  vars:
    containerd_version: "1.6.9"
    kubernetes_version: "1.28.2"
    calico_version: "3.27.2"
    ansible_connection_timeout: 300


